### ISSUE TITLE
US5 - Offline artifact analysis

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/project-management#13]
**Description:** To bolster security measures and guarantee a sufficient level of confidentiality, Colander will allow the offline analysis of artifacts using antivirus software and user-defined Yara rules. In the context of forensic analysis, this is crucial to be able to locally analyze extracted files (without relying on 3rd-party services) to ensure case confidentiality.

**Tasks:** 

- [ ] PiRogueToolSuite/project-management#14 
- [ ] PiRogueToolSuite/project-management#15
- [ ] PiRogueToolSuite/project-management#42
