### ISSUE TITLE
US9 - PiRogue virtualization

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/project-management#35]
**Description:** We want to provide end users with OS images and installation procedure allowing them to deploy PiRogue in a virtual environment (VM, cloud...). One of the direct implication is supporting a vast variety of configuration such as:
* Eth - Eth
* Wi-Fi - Eth
* VPN - Eth
* Wi-Fi - USB tethering

**Tasks:**

- [x] PiRogueToolSuite/project-management#40
- [x] PiRogueToolSuite/project-management#28 
- [x] PiRogueToolSuite/project-management#29 
- [x] PiRogueToolSuite/project-management#30 
- [x] PiRogueToolSuite/project-management#31
